# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 463)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_Folder = QtWidgets.QLabel(self.groupBox)
        self.label_Folder.setObjectName("label_Folder")
        self.gridLayout_4.addWidget(self.label_Folder, 0, 0, 1, 1)
        self.lineEdit_Folder = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Folder.setObjectName("lineEdit_Folder")
        self.gridLayout_4.addWidget(self.lineEdit_Folder, 0, 1, 1, 1)
        self.pushButton_Folder = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Folder.setObjectName("pushButton_Folder")
        self.gridLayout_4.addWidget(self.pushButton_Folder, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.lineEdit_Prefix = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Prefix.setObjectName("lineEdit_Prefix")
        self.gridLayout_4.addWidget(self.lineEdit_Prefix, 1, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_Merged = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Merged.setChecked(True)
        self.checkBox_Merged.setTristate(False)
        self.checkBox_Merged.setObjectName("checkBox_Merged")
        self.gridLayout_2.addWidget(self.checkBox_Merged, 0, 0, 1, 1)
        self.checkBox_Option = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Option.setObjectName("checkBox_Option")
        self.gridLayout_2.addWidget(self.checkBox_Option, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 2, 0, 2, 2)
        self.pushButton_Gen = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Gen.setObjectName("pushButton_Gen")
        self.gridLayout_4.addWidget(self.pushButton_Gen, 3, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_Parsers = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Parsers.setObjectName("groupBox_Parsers")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_Parsers)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3.addWidget(self.groupBox_Parsers, 1, 0, 1, 1)
        self.textBrowser_Consol = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_Consol.setObjectName("textBrowser_Consol")
        self.gridLayout_3.addWidget(self.textBrowser_Consol, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Folder.setText(_translate("MainWindow", "Folder:"))
        self.pushButton_Folder.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "Prefix:"))
        self.lineEdit_Prefix.setText(_translate("MainWindow", "Default"))
        self.checkBox_Merged.setText(_translate("MainWindow", "Mergred"))
        self.checkBox_Option.setText(_translate("MainWindow", "Show Options"))
        self.pushButton_Gen.setText(_translate("MainWindow", "Generate"))
        self.groupBox_Parsers.setTitle(_translate("MainWindow", "Parsers"))
